# Generated by Django 4.2.4 on 2023-10-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_mundial', '0002_equipo_evento_fase_jugador_mundial_participante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='formacion',
            field=models.CharField(choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('3-5-2', '3-5-2')], max_length=10),
        ),
    ]
