# Generated by Django 4.2.4 on 2023-10-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion_mundial', '0003_alter_pais_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('Delantero', 'Delantero'), ('Mediocampista', 'Mediocampista'), ('Defensor', 'Defensor'), ('Arquero', 'Arquero')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pais',
            name='formacion',
            field=models.CharField(choices=[('4-4-2', '4-4-2'), ('4-3-3', '4-3-3'), ('3-5-2', '3-5-2'), ('4-2-4', '4-2-4'), ('4-2-3-1', '4-2-3-1'), ('4-3-2-1', '4-3-2-1'), ('3-4-3', '3-4-3')], default='4-4-2', max_length=10),
        ),
        migrations.AlterField(
            model_name='pais',
            name='liga_nombre',
            field=models.CharField(max_length=150),
        ),
    ]
